//
//  YummyZoneSession.h
//  YummyZone
//
//  Created by Mustafa Demirhan on 2/14/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "ASIHTTPRequest.h"

@interface YummyZoneSession : NSObject
{
    NSMutableDictionary *_httpHeaders;
    NSOperationQueue *_queue;
    
    NSString *_username;
    NSString *_password;
    NSString *_cookie;
    BOOL _isAutogenerated;
    BOOL _signupComplete;
    
    BOOL _settingsEnableFacebook;
    BOOL _settingsEnableTwitter;
}

+ (YummyZoneSession*)singleton;
- (NSString*)obtainAuthorizationCookie;
- (NSString*)singinAndMergeTemporaryAccount:(NSString*)username password:(NSString*)password;
- (NSString*)signupAndMergeTemporaryAccount:(NSString*)username password:(NSString*)password;
- (BOOL)isUsingTemporaryAccount;
- (NSString*)getUserName;

- (NSDictionary*)getHttpHeaders;
- (void)queueAsyncRequest:(NSURL*)url useDefaultHeaders:(BOOL)useDefaultHeaders;
- (void)requestDone:(ASIHTTPRequest *)request;
- (void)requestWentWrong:(ASIHTTPRequest *)request;

- (void) updateSettingsWith:(NSDictionary*) dict;
- (BOOL) getSettingsEnableFacebook;
- (void) setSettingsEnableFacebook:(BOOL)enableFacebook;
- (BOOL) getSettingsEnableTwitter;
- (void) setSettingsEnableTwitter:(BOOL)enableTwitter;

@end
