USE [master]
GO

CREATE DATABASE [YummyZone];
GO

ALTER DATABASE [YummyZone] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
	EXEC [YummyZone].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [YummyZone] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [YummyZone] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [YummyZone] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [YummyZone] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [YummyZone] SET ARITHABORT OFF 
GO

ALTER DATABASE [YummyZone] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [YummyZone] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [YummyZone] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [YummyZone] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [YummyZone] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [YummyZone] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [YummyZone] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [YummyZone] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [YummyZone] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [YummyZone] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [YummyZone] SET  DISABLE_BROKER 
GO

ALTER DATABASE [YummyZone] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [YummyZone] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [YummyZone] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [YummyZone] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [YummyZone] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [YummyZone] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [YummyZone] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [YummyZone] SET  READ_WRITE 
GO

ALTER DATABASE [YummyZone] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [YummyZone] SET  MULTI_USER 
GO

ALTER DATABASE [YummyZone] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [YummyZone] SET DB_CHAINING OFF 
GO


